server:
  port: ${SERVER_PORT:8080}

spring:
  profiles: dev
  application:
    name: registration
  datasource:
    password: ${H2DB_PASSWORD:}
    url: jdbc:h2:mem:h2db
    username: ${H2DB_USERNAME:sa}
    driverClassName: org.h2.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: false

  sql:
    init:
      mode: always

message:
  exception:
    email-already-exists: ${MESSAGE_EXCEPTION_EMAIL_EXIST:Email already exists}
    illegal-salary: ${MESSAGE_EXCEPTION_ILLEGAL_SALARY:Minimum salary for new member is 15,000}
  success: ${MESSAGE_SUCCESSFUL:Successful}

